# ------ Default 
weight_decay: 5.0e-4
decay_type: "linear"
epochs: 100
lr : 3.0e-4
seed : 0
beta_1 : 0.5
beta_2 : 0.99
train_batch_size: 256
test_batch_size: 16
patch_size : 2
patch_margin : 4
emb_size : 144
pos_emb_size : 2
latent_size : 1
warmup_steps : 100
random_seed : 0
eval_every : 10
# ------ Dataset
dataset: 'emnist'
dataset_2:
  first : 'mnist'
  second : 'emnist'
  third : 'fashion' 
pin_memory : True
num_classes : 10
img_size : 32
num_workers : 8
grayscale : True
loss_beta : 3.0e-3
# Validation Setting"""
interval_val : 1 

# Save Path"""
ckpt_fpath : '../experiments/generator/emnist'

# WANDB SETTINGS"""
wandb:
  project : 'generator_EMNIST'
  id : 'jonggyujang0123'
  name : 'ResNet50_lr'
  active : True
