# ------ Default 
weight_decay: 5.0e-4
decay_type: "cosine"
use_amp: False        # Use automatic mixed precision
epochs: 30
lr : 3.0e-2
seed : 0
warmup_steps : 100
random_seed : 0
# ------ Dataset
dataset: 'mnist'
train_batch_size: 32
test_batch_size: 32
pin_memory : True
num_classes : 10
img_size : 32
num_workers : 8
grayscale : True

# Validation Setting"""
interval_val : 1 

# Save Path"""
ckpt_fpath : '../experiments/classifier/mnist'

# WANDB SETTINGS"""
wandb:
  project : 'classifier_MNIST'
  id : 'jonggyujang0123'
  name : 'ResNet50_lr'
  active : True
