# ------ Default 
weight_decay: 5.0e-4
decay_type: "linear"
epochs: 8000
lr : 3.0e-3
seed : 3
beta_1 : 0.5
beta_2 : 0.999
train_batch_size: 1024
test_batch_size: 256
patch_size : 4
patch_margin : 0
emb_size : 144
pos_emb_size : 2
n_gf : 16
latent_size : 10
warmup_steps : 100
random_seed : 0
# ------ Dataset
dataset: 'fashion'
dataset_2:
  first : 'mnist'
  second : 'emnist'
  third : 'fashion' 
pin_memory : True
num_classes : 10
img_size : 32
num_workers : 8
grayscale : True
num_channel : 1
attack_labelsmooth : 0.0
freeze_every : 10
# Validation Setting"""
interval_val : 200
kl_every : 1
lambda_attack : 1.0
lambda_miner_entropy : 0.0e-1
lambda_kl : 1.0e-3
# Save Path"""
ckpt_fpath : '../experiments/attacker/emnist'
ckpt_fpath_generator : '../experiments/generator/emnist_cgan'
#ckpt_fpath_generator : '../experiments/generator/emnist'
ckpt_fpath_class : '../experiments/classifier/mnist'

# WANDB SETTINGS"""
wandb:
  project : 'PVMI_MNIST'
  id : 'jonggyujang0123'
  name : 'ResNet50'
  active : True
