# ------ Default 
weight_decay: 5.0e-4
decay_type: "linear"
epochs: 30
lr : 1.0e-3
seed : 3
beta_1 : 0.5
beta_2 : 0.999
train_batch_size: 256
test_batch_size: 100
patch_size : 4
patch_margin : 4
n_gf : 64
n_df : 64
latent_size : 100
embed_dim : 10
warmup_steps : 100
random_seed : 0
w_attack : 0.3
eval_every : 1
n_classes : 10
# ------ Dataset
dataset: 'emnist'
dataset_2:
  first : 'mnist'
  second : 'emnist'
  third : 'fashion' 
pin_memory : True
num_classes : 10
img_size : 32
num_workers : 8
grayscale : True
num_channel : 1
attack_labelsmooth : 0.0
freeze_every : 10
# Validation Setting"""
interval_val : 200
kl_every : 1
# Save Path"""
ckpt_fpath : '../experiments/attacker/emnist'
ckpt_fpath_generator : '../experiments/generator/emnist_cgan'
#ckpt_fpath_generator : '../experiments/generator/emnist'
ckpt_fpath_class : '../experiments/classifier/mnist'

# WANDB SETTINGS"""
wandb:
  project : 'PVMI_MNIST'
  id : 'jonggyujang0123'
  name : 'ResNet50'
  active : True
